FROM alpine:3.15.0 as stage_1
RUN touch /tmp/first.txt
RUN sleep 6


FROM alpine:3.15.0 as stage_2
RUN touch /tmp/second.txt
RUN sleep 6


FROM alpine:3.15.0 as stage_3
RUN touch /tmp/third.txt
RUN sleep 6


FROM alpine:3.15.0 as final
COPY --from=stage_1 /tmp/first.txt /tmp/
COPY --from=stage_2 /tmp/second.txt /tmp/
COPY --from=stage_3 /tmp/third.txt /tmp/
